### ISSUE TITLE
Web Crawling

### ISSUE THREAD

**Issue by HyunjoonCho** [HyunjoonCho/CS492I-IntroToDL-project#2]
Must consider **legal issues**!  
List related posts

* [합법적으로 ‘웹 크롤링’하는 방법 (上)](https://yozm.wishket.com/magazine/detail/877/?fbclid=IwAR0rsDcmwHeqJLQaOTvKAZtpukAYIzBlNhVezzXsVb25xpqQ9dStsuVXaeI)

**Comment by HyunjoonCho** [comment]
## IMPORTFEED
구글 스프레드시트에서 IMPORTFEED 함수를 호출해서 바로 기사를 긁어오는 기능이 있음  
다음 [블로그 포스트](https://brunch.co.kr/@sijin90/52) 참고  

다음은 [직접 돌려본 결과](https://docs.google.com/spreadsheets/d/1BcXCpndfipia4hMycQB9vvBNVyOlQRn4YlsDQrvlqVc/edit?usp=sharing)  

몇 가지 특징으로
* header parsing(title, date created)을 자동으로 해주며
* Summary column을 자체적으로 제공함! 다만, 하나씩 살펴보니 대부분 제목과 일치하는 수준..

추가로 살펴볼 사항은
* IMPORTFEED로 어디까지 할 수 있는지
  * summary 외에 본문도 긁어올 수 있는지
  * 날짜, 언론사 등을 제한할 수 있는지; url의 query 부분을 손 보면 가능할 것으로 예상됨 
* spreadsheet to csv/txt; 이건 간단할듯
* 위 legal issue는 여전히 별도의 문제

**Comment by HyunjoonCho** [comment]
## Scrpaing
> 기본적으로 웹 크롤링은 기존의 복사본을 만들고, 웹 스크래핑은 분석을 위한 특정 데이터를 추출하거나 새로운 것을 만듭니다.  

크롤링은 본문 그대로 가져오고, 스크래핑은 parsing, processing까지 포괄하는듯
* 네이버 뉴스: [Ref](https://serpapi.com/blog/scrape-naver-news-results-with-python/), 오히려 바로 돌리기 쉬운듯?

* 구글 뉴스: [Ref](https://serpapi.com/blog/scrape-google-news-with-python/)

**Comment by HyunjoonCho** [comment]
## Implementing Simple Scraper
* Source: Google News RSS e.g. https://news.google.com/rss/search?q=삼성전자+when:1d&hl=ko&gl=KR&ceid=KR:ko
  * RSS = Rich Site Summary
* Steps
  1. Selenium 설치: 운영체제에 맞춰 chrome driver
  2. BeautifulSoup 설치: RSS는 xml format, BS는 기본적으로 HTML으로 parsing  
      xml parsing 하려면 lxml 추가 설치 필요 [Ref](https://www.crummy.com/software/BeautifulSoup/bs4/doc/#parser-installation)
  3. xml 항목별로 형태 확인해서 추가적인 parsing 작업 진행
      * description에 포함된 href, font 등은 삭제
  4. pandas data frame에 담아서 to csv *_필요시 txt로 변경_

### TODOs
- [ ] datetime parsing
- [ ] 제목 parsing 시 언론사 제거
    *  고민: description과 제목이 일치하는 경우가 많음
- [ ] 뉴스 검색시에 날짜 지정하는 법 파악 *_휴장일은 제외_
- [ ] FDR module 사용해서 해당 날짜 및 전거래일의 주가 가져오기, 변동폭 계산
- [ ] 기사 filtering - 다 concat해서 돌려보고 차츰 개선해나가는 쪽으로

**Comment by HyunjoonCho** [comment]
## Article Filtering
* 기업명을 정확히 포함할 때만 수집 - NAVER, POSCO 등 정식 사명이 관용명과 일치하지 않는 경우
* 그냥 다 받으면 크게 관련 없는 기사, 계열사에 대한 기사 등이 포함됨 e.g. KT&G -> KT 야구단
## Timing Issue
주가 변동에 대해서 (전거래일) - (당일) 사이에 발행된 기사를 수집  
이때 google news rss의 특징인지 기사 업로드 시점이 08:00으로 통일됨  
개중에 장 종료 후 업데이트된 것도 섞여 있음
